name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
assignees: []

body:
- type: markdown
    attributes:
        value: |
            **Is your feature request related to a problem? Please describe.**
- type: textarea
    id: problem-description
    attributes:
        label: Problem Description
        description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

- type: markdown
    attributes:
        value: |
            **Describe the solution you'd like**
- type: textarea
    id: solution-description
    attributes:
        label: Solution Description
        description: A clear and concise description of what you want to happen.

- type: markdown
    attributes:
        value: |
            **Describe alternatives you've considered**
- type: textarea
    id: alternatives-description
    attributes:
        label: Alternatives Description
        description: A clear and concise description of any alternative solutions or features you've considered.

- type: markdown
    attributes:
        value: |
            **Additional context**
- type: textarea
    id: additional-context
    attributes:
        label: Additional Context
        description: Add any other context or screenshots about the feature request here.
